[project]
name = "Hello"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "C:\\Users\\Eqan Ahmad\\.clarinet\\cache"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.Hello]
path = "contracts/Hello.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
